
Importation des données.

```{r}
setwd('C:/Users/ameli/OneDrive/Documents/M2/Visualisation/Projet')
# Espérance de vie
dta_esp <- read.csv("LifeExpectancyData.csv", stringsAsFactors = T)
dta_esp$Year <- as.factor(dta_esp$Year)
colnames(dta_esp)
```

Polio, listeria, hepatitis B, BMI

```{r}
dta_esp <- dta_esp[,c(1,2,4,9,11,13,15,16)]

# Codes ISO3
code <- read_excel("CodeISO3.xlsx")
code$ISO3 <- as.factor(code$ISO3)

# GDP
dta_GDP <- read.csv("GDP_data.csv", sep=",", stringsAsFactors = T)
dta_GDP <- dta_GDP[,3:20]
colnames(dta_GDP) <- c("Country","ISO3","2000", "2001", "2002","2003", "2004", "2005","2006", "2007", "2008","2009","2010", "2011", "2012","2013", "2014", "2015")

dta_GDP <- dta_GDP %>% 
  pivot_longer(c("2000", "2001", "2002","2003", "2004", "2005","2006", "2007", "2008","2009","2010", "2011", "2012","2013", "2014", "2015"))
colnames(dta_GDP)[3:4] <- c("Year", "GDP")
dta_GDP$Year <- as.factor(dta_GDP$Year)

# Dépenses par personne
dta_dep <- read.csv("Dep_data.csv", sep=",", stringsAsFactors = T)
dta_dep <- dta_dep[,3:20]
colnames(dta_dep) <- c("Country","ISO3","2000", "2001", "2002","2003", "2004", "2005","2006", "2007", "2008","2009","2010", "2011", "2012","2013", "2014", "2015")

dta_dep <- dta_dep %>% 
  pivot_longer(c("2000", "2001", "2002","2003", "2004", "2005","2006", "2007", "2008","2009","2010", "2011", "2012","2013", "2014", "2015"))
colnames(dta_dep)[3:4] <- c("Year", "Depense")
dta_dep$Year <- as.factor(dta_dep$Year)
```

Merge des jeux de données.

```{r}
dta_esp <- left_join(dta_esp, code, by = "Country")
dta_esp <- dta_esp[,-1]

dta <- left_join(dta_esp, dta_dep, by = c("ISO3","Year"))

dta_GDP <- dta_GDP[,-1]
dta <- left_join(dta, dta_GDP, by = c("ISO3","Year"))

```

Calcul des différences des espérance de vie.

```{r}
dta.diff <- dta %>% 
  group_by(ISO3) %>%
  summarise(Life.expectancy.diff = Life.expectancy[Year=='2015'] - Life.expectancy[Year=='2000'], Depense.diff = Depense[Year=='2015'] - Depense[Year=='2000'], GDP.diff = GDP[Year=='2015'] - GDP[Year=='2000']) %>%
  arrange(Life.expectancy.diff)
```


# Visu 2 : Evolution des indicateurs

```{r, warning=F}
# Evolution depense en santé
ggplot(data = dta, 
       aes(x = Year, y = Depense, group = Country)) + 
  
  geom_line(aes(color = Country)) +
  
  geom_point(aes(color = Country)) +
  
  theme(legend.position = "none")  # pas de légende


# Evolution GDP
ggplot(data = dta, 
       aes(x = Year, y = round(GDP), group = Country)) + 
  
  geom_line(aes(color = Country)) +
  
  geom_point(aes(color = Country)) +
  
  theme(legend.position = "none")  # pas de légende
```


```{r}
expectancy <- inner_join(dta, dta.diff, by='ISO3')
n_distinct(expectancy[,1]) #183 pays pour lesquels ont a la valeur de la difference
colnames(expectancy)
```

```{r}
test <- expectancy %>% filter(Depense.diff<0)
test[,c(4,7:9)]
```

```{r}

expectancy.2000 <- expectancy %>% filter(Year==2000)

expectancy.2000[,5]<-round(expectancy.2000[,5],1)
expectancy.2000[,6]<-round(expectancy.2000[,6],1)
expectancy.2000[,8]<-round(expectancy.2000[,8],1)
expectancy.2000[,9]<-round(expectancy.2000[,9],1)

summary(expectancy.2000)

g1 <- ggplotly(ggplot(data = expectancy.2000, 
       aes(x = Depense.diff, y = Life.expectancy.diff, text=paste("Pays : ",Country,"<br>Espérance de vie en 2000 : ", Life.expectancy, "<br>Dépenses en santé en 2000 : ", Depense," USD")), na.rm=TRUE) +
  geom_point(aes(color=Life.expectancy, size=Depense)) +
  scale_color_gradient(low ="#FFFF99",high = "#009933") +
  scale_y_continuous(breaks=seq(-10, 20, 5)) +
  scale_x_continuous(breaks=seq(0, 6000, 1000)) +
  labs(x = "Différences des dépenses en santé par habitant entre 2000 et 2015 (USD)",
    y = "Différences d'espérance de vie entre 2000 et 2015",
    colour = "Espérance de vie",
    size = "Dépenses en santé \n par habitant") +
    ggtitle("Représentation de la relation espérance de vie - dépense en santé") +
  theme(plot.title = element_text(face="bold", hjust=0.5, size=10), 
                     axis.title.x = element_text(size=9),
                     axis.title.y = element_text(size=9),
        panel.background = element_rect(fill = "white"),
        panel.grid.major = element_line(colour = "#CCCCCC"),
        plot.margin = unit(c(1,1,1,1), "cm")), tooltip="text")
  
g1 %>% layout(showlegend=TRUE)

g2 <- ggplotly(ggplot(data = expectancy.2000, 
       aes(x = GDP.diff, y = Life.expectancy.diff, text=paste("Pays : ",Country,"<br>Espérance de vie en 2000 : ", Life.expectancy, "<br>GDP en 2000 : ", GDP)), na.rm=TRUE) +
  geom_point(aes(color=Life.expectancy, size=GDP)) +
  scale_color_gradient(low ="#FFFF99",high = "#009933") +
  scale_y_continuous(breaks=seq(-10, 20, 5)) +
  scale_x_continuous(breaks=seq(-10000, 60000, 10000)) +
  labs(x = "Différences de GDP par habitant entre 2000 et 2015",
    y = "Différences d'espérance de vie entre 2000 et 2015",
    colour = "Espérance de vie",
    size = "GDP par habitant") +
    ggtitle("Représentation de la relation espérance de vie - GDP") +
  theme(plot.title = element_text(face="bold", hjust=0.5, size=10), 
                     axis.title.x = element_text(size=9),
                     axis.title.y = element_text(size=9),
        panel.background = element_rect(fill = "white"),
        panel.grid.major = element_line(colour = "#CCCCCC"),
        plot.margin = unit(c(1,1,1,1), "cm")), tooltip="text")
  
g2 %>% layout(showlegend=TRUE)
```

```{r}
ggplotly(ggplot(data = expectancy.2000, 
       aes(x = Depense.diff, y = Life.expectancy.diff, text=Country), na.rm=TRUE) +
  geom_point(aes(color=Life.expectancy, size=Depense)) +
  scale_color_gradient(low ="#FFFF99",high= "#009933") +
    scale_y_continuous(breaks=seq(-10, 20, 5)) +
  scale_x_continuous(breaks=seq(0, 6000, 1000))+
  labs(x = "Différences de dépense en santé par habitant entre 2000 et 2015",
    y = "Différences d'espérance de vie entre 2000 et 2015",
    colour = "Espérance de vie",
    size = "Dépenses en santé \n par habitant") +
    ggtitle("Représentation de la relation espérance de vie - dépense en santé") +
  theme(plot.title = element_text(face="bold", hjust=0.5, size=10), 
                     axis.title.x = element_text(size=9),
                     axis.title.y = element_text(size=9),
        panel.background = element_rect(fill = "white"),
        panel.grid.major = element_line(colour = "#CCCCCC"),
        plot.margin = unit(c(1,1,1,1), "cm")) +
    guides(color = guide_legend(order = 1), size = guide_legend(order = 2)))
```




```{r}
p <- plot_ly(data = expectancy.2000, x = ~Depense.diff, y = ~Life.expectancy.diff,
        type = "scatter", mode = "markers", color=~Life.expectancy, size=~Depense,
        text = ~paste(Country, "<br>Dépenses en santé \n par habitant: ", Depense, '<br>Espérance de vie:', Life.expectancy)) %>%
  layout(showlegend = T, yaxis = list(title = "Différence d'espérance de vie entre 2000 et 2015"), showlegend = T, xaxis =list(title = "Différence de dépense en santé par habitant entre 2000 et 2015"), showlegend = T)
p %>% layout(title = "Représentation de la relation espérance de vie - dépense en santé")
```



```{r}
 plot_ly(data = expectancy.2015, x = ~reorder(Country,Life.expectancy), y = ~Life.expectancy, name = "Life Expectancy", type = 'scatter') %>%
  add_trace(y = ~GDP, name = "GDP", mode="markers", yaxis = "y2", mode="markers")%>%
  layout(title = "Correlation between Murder Rate and Illiteracy VS Life Expection", 
         xaxis = list(title="Country"),
         yaxis = list(tickfont= list(color = '#1f77b4', size=11), color='#1f77b4', range=c(0,4),
                      title="Life Expectation"),
         yaxis2 = list(overlaying = "y", side = "right",
                       tickfont = list(color = '#ff7f0e', size=11), color='#ff7f0e', range=c(67.8,73.8),
                       title = "GDP"),
         legend = list(x = 1.05, y = 0.9))
```



```{r}
ggplot(data = dta.diff, 
       aes(x = Depense.diff, y = Life.expectancy.diff))+
  geom_point()

ggplot(data = dta.diff, 
       aes(x = GDP.diff, y = Life.expectancy.diff))+
  geom_point()
```



```{r}
dta.2015 <- dta %>% 
  filter(Year=="2015")

ggplot(data = dta.2015, 
       aes(x = Depense, y = Life.expectancy))+
  geom_point()

ggplot(data = dta.2015, 
       aes(x = GDP, y = Life.expectancy))+
  geom_point()
```


Evolution des dépenses selon les diffs

```{r}
expectancy.diff.neg <- expectancy %>% filter(Life.expectancy.diff<0)
n_distinct(expectancy.diff.neg[,1])#9 pays

ggplot(data = expectancy.diff.neg, 
       aes(x = Year, y = Depense, group = Country), na.rm=TRUE) + 
  
  geom_line(aes(color = Country)) +
  
  geom_point(aes(color = Country)) 
```


```{r}
expectancy.diff.2 <- expectancy %>% filter((Life.expectancy.diff>=0)&(Life.expectancy.diff<2.5))
n_distinct(expectancy.diff.2[,1])#32 pays

ggplot(data = expectancy.diff.2, 
       aes(x = Year, y = Depense, group = Country)) + 
  
  geom_line(aes(color = Country)) +
  
  geom_point(aes(color = Country))
```

```{r}
expectancy.diff.5 <- expectancy %>% filter((Life.expectancy.diff>2.5)&(Life.expectancy.diff<5))
n_distinct(expectancy.diff.5[,1])#74 pays

ggplot(data = expectancy.diff.5, 
       aes(x = Year, y = Depense, group = Country)) + 
  
  geom_line(aes(color = Country)) +
  
  geom_point(aes(color = Country)) 
```


```{r}
expectancy.diff.10 <- expectancy %>% filter((Life.expectancy.diff>5)&(Life.expectancy.diff<10))
n_distinct(expectancy.diff.10[,1])#41 pays

ggplot(data = expectancy.diff.10, 
       aes(x = Year, y = Depense, group = Country)) + 
  
  geom_line(aes(color = Country)) +
  
  geom_point(aes(color = Country)) 
```


```{r}
expectancy.diff.plus <- expectancy %>% filter(Life.expectancy.diff>10)
n_distinct(expectancy.diff.plus[,1])#34 pays

ggplot(data = expectancy.diff.plus, 
       aes(x = Year, y = Depense, group = Country)) + 
  
  geom_line(aes(color = Country)) +
  
  geom_point(aes(color = Country)) 
```

Evolution du GDP en fonction des diffs

```{r}
expectancy.diff.neg <- expectancy %>% filter(Life.expectancy.diff<0)
n_distinct(expectancy.diff.neg[,1])#9 pays

ggplot(data = expectancy.diff.neg, 
       aes(x = Year, y = GDP, group = Country)) + 
  
  geom_line(aes(color = Country)) +
  
  geom_point(aes(color = Country)) 
```

```{r}
expectancy.diff.2 <- expectancy %>% filter((Life.expectancy.diff>=0)&(Life.expectancy.diff<2.5))
n_distinct(expectancy.diff.2[,1])#32 pays

ggplot(data = expectancy.diff.2, 
       aes(x = Year, y = GDP, group = Country)) + 
  
  geom_line(aes(color = Country)) +
  
  geom_point(aes(color = Country))
```

```{r}
expectancy.diff.5 <- expectancy %>% filter((Life.expectancy.diff>2.5)&(Life.expectancy.diff<5))
n_distinct(expectancy.diff.5[,1])#74 pays

ggplot(data = expectancy.diff.5, 
       aes(x = Year, y = GDP, group = Country)) + 
  
  geom_line(aes(color = Country)) +
  
  geom_point(aes(color = Country)) 
```

```{r}
expectancy.diff.10 <- expectancy %>% filter((Life.expectancy.diff>5)&(Life.expectancy.diff<10))
n_distinct(expectancy.diff.10[,1])#41 pays

ggplot(data = expectancy.diff.10, 
       aes(x = Year, y = GDP, group = Country)) + 
  
  geom_line(aes(color = Country)) +
  
  geom_point(aes(color = Country)) 
```

```{r}
expectancy.diff.plus <- expectancy %>% filter(Life.expectancy.diff>10)
n_distinct(expectancy.diff.plus[,1])#34 pays

ggplot(data = expectancy.diff.plus, 
       aes(x = Year, y = GDP, group = Country)) + 
  
  geom_line(aes(color = Country)) +
  
  geom_point(aes(color = Country)) 
```



```{r, warning=F}
# Evolution depense en santé
ggplot(data = dta, 
       aes(x = Year, y = Hepatitis.B, group = Country)) + 
  
  geom_line(aes(color = Country)) +
  
  geom_point(aes(color = Country)) +
  
  theme(legend.position = "none")  # pas de légende

```

```{r, warning=F}
# Evolution depense en santé
ggplot(data = dta, 
       aes(x = Year, y = BMI, group = Country)) + 
  
  geom_line(aes(color = Country)) +
  
  geom_point(aes(color = Country)) +
  
  theme(legend.position = "none")  # pas de légende

```


```{r, warning=F}
# Evolution depense en santé
ggplot(data = dta, 
       aes(x = Year, y = Polio, group = Country)) + 
  
  geom_line(aes(color = Country)) +
  
  geom_point(aes(color = Country)) +
  
  theme(legend.position = "none")  # pas de légende

```